### ISSUE TITLE
binder

### ISSUE THREAD

**Issue by TInkara25** [TInkara25/APPR-2019-20#2]
Pozdravljeni!

Posodobila sem povezavo za binder, ki pa trenutno ne deluje. Binder se zažene, vendar se moje poročilo ne prikaže in mi sporoči napako. Kaj moram popraviti?

**Comment by timotejvesel** [comment]
Popraviti moraš napake, ki so v poročilu in v kodi. Iz poročila moraš odstraniti vzorčno kodo, napaka je še v vrstici 148 v datoteki `uvoz.r` in mogoče še kje. Zaženi vsako datoteko posebej in boš videla kje so napake.

**Comment by jaanos** [comment]
Svetujem, da pretvorbo v *tidy data* namesto z `melt` opraviš s `pivot_longer` (poglej si vaje na letošnjem Tomu za primer), saj se ta obnaša konsistentno ne glede na različico R in imena stolpcev vedno predstavi kot nize namesto faktorjev - tako lahko letnice v števila pretvoriš s `parse_number`. Ta nekonsistentnost (verjetno zaradi različnih verzij R) je tudi razlog, da poročilo ne deluje na Binderju.

**Comment by TInkara25** [comment]
Popravila sem ukaza pivot_longer in parse_number v dateteki uvoz.r in ostale napake, ki sem jih našla. Ko zaženem datoteke vsako posebej mi program ne vrača nobenih napak, vendar Binder še vedno ne deluje. Kaj je lahko še narobe?

**Comment by timotejvesel** [comment]
Da bo poročilo delovalo v Binderju, mora delovati tudi lokalno v RStudiu. Če ga odpreš tam, ti tudi napiše kje je napaka. V tvojem primeru *Error: duplicate label 'graf4'*.  Torej se ponavlja ime oznake bloka, kjer uvoziš `graf4` in `graf6`. Podobno se podvaja tudi oznaka `graf5`. 

Priporočam še, da preimenuješ imena stolpcev v tabelah, da ne bodo vsebovala šumnikov ter presledkov.

**Comment by TInkara25** [comment]
Trenutno v mojem RStudiu poročilo deluje (razen zadnjega zemljevida), vendar pa na Binderju še vedno dobimo napako.

**Comment by timotejvesel** [comment]
Če odprem kodo v Binderju javlja napako v funkciji `pivot_longer`. Če zamenjaš `!"Kaznivo dejanje"` z `-c("Kaznivo dejanje")` (podobno tudi v ostalih funkcijah) bi moralo delovati.

**Comment by TInkara25** [comment]
Sem popravila in deluje. Najlepša hvala za pomoč.
